import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // containerized build output (see next.config.ts's distDir).
    ".next-container/**",
    // generated by `eshop generate types` - see lib/types.ts.
    "lib/api-schema.d.ts",
  ]),
]);

export default eslintConfig;
