<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <IsPackable>true</IsPackable>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>HenrikJensen.ReverseProxy</PackageId>
    <Description>Pairs Microsoft YARP with a web API for runtime configuration and automatic self-signed certificates.</Description>
    <PackageTags>testing;reverse-proxy;certificates</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Version>2.0.0-beta</Version>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="System.Net" />
    <Using Include="System.Security.Cryptography" />
    <Using Include="System.Security.Cryptography.X509Certificates" />
    <Using Include="Microsoft.Extensions.Configuration" />
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Microsoft.Extensions.Options" />
  </ItemGroup>

    <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>$(MSBuildProjectName).UnitTest</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
  </ItemGroup>

</Project>
