<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/migrations/EShop.Migrations.Common/EShop.Migrations.Common.csproj" />
    <ProjectReference Include="../EShop.Testing.Common/EShop.Testing.Common.csproj" />
  </ItemGroup>

</Project>
