// <auto-generated />
using System;
using Hj.EShop.SellerPortal.Bff.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hj.EShop.SellerPortal.Bff.Data.Migrations
{
    [DbContext(typeof(SellerPortalDbContext))]
    [Migration("20260916113721_Aspire1353EfCoreUpgrade")]
    partial class Aspire1353EfCoreUpgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DraftKind")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("LastRejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Drafts");

                    b.HasDiscriminator<string>("DraftKind").HasValue("Draft");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.SellerInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReportedQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellerId", "Sku")
                        .IsUnique();

                    b.ToTable("SellerInventories");
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedSku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KindSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("ProposedSku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.HasIndex("SellerId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.MerchandiseDraft", b =>
                {
                    b.HasBaseType("Hj.EShop.SellerPortal.Bff.Data.Entities.Draft");

                    b.Property<string>("AssociatedMovieTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Merchandise");
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.MovieDraft", b =>
                {
                    b.HasBaseType("Hj.EShop.SellerPortal.Bff.Data.Entities.Draft");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.ToTable("Drafts", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("MovieDraft_Description");
                        });

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.Draft", b =>
                {
                    b.HasOne("Hj.EShop.SellerPortal.Bff.Data.Entities.Seller", "Seller")
                        .WithMany("Drafts")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Hj.EShop.SellerPortal.Bff.Data.Entities.DraftImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BlobReference")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("DraftId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Position")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("DraftId");

                            b1.ToTable("DraftImage");

                            b1.WithOwner()
                                .HasForeignKey("DraftId");
                        });

                    b.Navigation("Images");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.SellerInventory", b =>
                {
                    b.HasOne("Hj.EShop.SellerPortal.Bff.Data.Entities.Seller", null)
                        .WithMany("Inventory")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.Submission", b =>
                {
                    b.HasOne("Hj.EShop.SellerPortal.Bff.Data.Entities.Draft", null)
                        .WithMany()
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hj.EShop.SellerPortal.Bff.Data.Entities.Seller", null)
                        .WithMany("Submissions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.MovieDraft", b =>
                {
                    b.OwnsMany("Hj.EShop.SellerPortal.Bff.Data.Entities.DraftFormatVariant", "FormatVariants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("DraftId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Format")
                                .HasColumnType("int");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("DraftId");

                            b1.ToTable("DraftFormatVariant");

                            b1.WithOwner()
                                .HasForeignKey("DraftId");
                        });

                    b.Navigation("FormatVariants");
                });

            modelBuilder.Entity("Hj.EShop.SellerPortal.Bff.Data.Entities.Seller", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("Inventory");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
