<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>602c428e-fc18-4962-afe6-6465b7708636</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
    <PackageReference Include="Aspire.Hosting.Azure.Redis" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" />
    <PackageReference Include="Aspire.Hosting.Azure.Sql" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Resilience" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../lib/DotNet-ReverseProxy/src/ReverseProxy.Aspire/ReverseProxy.Aspire.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../shared/EShop.Common/EShop.Common.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../dev/EShop.DevTools/EShop.DevTools.csproj" />
    <ProjectReference Include="../dev/EShop.ReverseProxy/EShop.ReverseProxy.csproj" />
    <ProjectReference Include="../apps/EShop.SellerPortal.Bff/EShop.SellerPortal.Bff.csproj" />
    <ProjectReference Include="../apps/EShop.SellerPortal.MigrationRunner/EShop.SellerPortal.MigrationRunner.csproj" />
    <ProjectReference Include="../apps/EShop.StoreFront.MigrationRunner/EShop.StoreFront.MigrationRunner.csproj" />
    <ProjectReference Include="../apps/EShop.StoreFront.Web/EShop.StoreFront.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EShop.AppHost.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Realms/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
